In [1]:
import numpy as np

In [10]:
# Write a NumPy program to create an array of all even integers from 30 to 70.

even_num = np.arange(30,70,2)

In [11]:
print(even_num)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


In [16]:
# Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

random_numbers = np.random.randn(15)

print(random_numbers)

[ 0.37941536 -1.29695977 -0.04410337  0.81793891 -0.07269532  0.80073981
 -0.88168362 -1.37519335 -0.46309102 -0.22246267  1.11160305  0.38778897
 -1.51460926 -0.08224021 -0.44187611]


In [27]:
# How to compute the cross-product of two matrices in NumPy?

matrix_one = np.array([[1,2,3],[4,5,6]])
matrix_two = np.array([[11,12,13],[14,15,16]])

cross_product = np.cross(matrix_one , matrix_two)
print(cross_product)

[[-10  20 -10]
 [-10  20 -10]]


In [33]:
# How to compute the determinant of an array using NumPy?
matrix_one = np.array([[1,2,3],[4,5,6],[7,8,9]])

determinant = np.linalg.det(matrix_one)
print(determinant)

-9.51619735392994e-16


In [36]:
# How to create a 3x3x3 array with random values using NumPy?

array_333 = np.random.randint(1,100,size=(3,3,3))
array_333

array([[[97,  8, 20],
        [62, 57, 58],
        [24, 11, 79]],

       [[92, 69, 52],
        [74, 91, 44],
        [66, 37, 27]],

       [[42, 64,  9],
        [95, 36, 35],
        [53, 20, 72]]])

In [37]:
# How to create a 5x5 array with random values and find the minimum and maximum values using NumPy?

array_55 = np.random.randint(1,600,size=(5,5))
print(array_55)
print("Max value: ",array_55.max())
print("Min value: ",array_55.min())

[[513 459 559 435 136]
 [560 597 236  42 567]
 [ 30  93 278 538 179]
 [ 64  83 396 129 160]
 [167 353 223 289 190]]
Max value:  597
Min value:  30


In [40]:
# How to compute the mean, standard deviation, and variance of a given array along the second axis in NumPy?

# Create a sample 2D array (3x4)
sample_array = np.array([[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]])

# mean along the second axis (axis=1)
mean_values = np.mean(sample_array, axis=1)

# standard deviation along the second axis (axis=1)
std_deviation_values = np.std(sample_array, axis=1)

# # variance along the second axis (axis=1)
variance_values = np.var(sample_array, axis=1)

print("Original Array:")
print(sample_array)

print("\nMean along the second axis:")
print(mean_values)


print("\nStandard Deviation along the second axis:")
print(std_deviation_values)

print("\nVariance along the second axis:")
print(variance_values)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Mean along the second axis:
[5. 6. 7. 8.]

Standard Deviation along the second axis:
[3.26598632 3.26598632 3.26598632 3.26598632]

Variance along the second axis:
[1.25 1.25 1.25]
